package com.vitalai.app.data.local.entity;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import com.vitalai.app.domain.model.enums.ChatRole;

import java.util.Date;

/**
 * ChatMessageEntity
 *
 * Room entity representing a row in the {@code chat_messages} table.
 * Each row records one message in the conversational AI chat feature —
 * either a message sent by the user or a response generated by the
 * VitalAI assistant (Claude / on-device model).
 *
 * Design notes
 * ────────────
 * • Foreign key to {@link UserEntity} uses ON DELETE CASCADE — deleting
 *   a user automatically removes their entire chat history without any
 *   manual Repository cleanup.
 *
 * • {@code role} maps to {@link ChatRole} — the originator of the message
 *   (USER or ASSISTANT). Stored as TEXT via TypeConverters. This mirrors
 *   the standard OpenAI / Anthropic message role convention so the chat
 *   history can be serialised directly into the AI API request body
 *   without transformation.
 *
 * • {@code sessionId} is a logical grouping key — a UUID string that
 *   groups all messages belonging to one continuous conversation thread.
 *   It is NOT a FK to a separate sessions table; conversations are
 *   intentionally schema-light (no fixed start/end, no title row) so
 *   the user can resume any prior thread without ceremony. The
 *   Repository derives the session list by a GROUP BY session_id query.
 *   A new UUID is generated by the Repository when the user taps
 *   "New Chat"; all subsequent messages in that thread share the same
 *   sessionId until another new chat is started.
 *
 * • {@code content} is the raw message text. For ASSISTANT messages this
 *   is the full model response including any markdown formatting. The UI
 *   layer renders markdown; the DB stores the raw string.
 *
 * • {@code contextSnapshot} is an optional JSON string capturing the
 *   subset of the user's health context injected into the system prompt
 *   for this message turn. Stored for two purposes:
 *     1. Debugging / explainability — the user can see exactly what
 *        health data the AI was given when it produced a response.
 *     2. Re-hydration — if the local DB is partially cleared, the
 *        context snapshot allows the AI layer to reconstruct the prompt
 *        without re-querying all child tables.
 *   Nullable — USER messages do not carry a context snapshot; only
 *   ASSISTANT messages do. Also null for messages generated before
 *   context snapshotting was introduced.
 *
 * • {@code isError} flags ASSISTANT messages where the model call failed
 *   (network timeout, API error, content filter rejection). The UI renders
 *   these with an error indicator and a "Retry" button. The message
 *   content in this case holds the user-facing error description.
 *   Always false for USER messages.
 *
 * • {@code tokenCount} is the number of tokens consumed by this message
 *   as reported by the AI API response. Stored for usage analytics,
 *   context-window budget management (the Repository trims history when
 *   cumulative tokens approach the model's context limit), and potential
 *   future per-user cost attribution. Nullable — not available for USER
 *   messages or for on-device model responses that don't report token
 *   counts.
 *
 * • {@code modelVersion} records the specific AI model that generated
 *   an ASSISTANT message. Null for USER messages. Mirrors the same field
 *   in {@link InsightEntity} for consistent model auditability across
 *   the app's AI-generated content.
 *   Examples: "claude-sonnet-4-20250514", "tflite-chat-v1.2"
 *
 * • {@code feedbackRating} captures explicit user feedback on an
 *   ASSISTANT message (thumbs up / thumbs down, represented as 1 / -1).
 *   Null until the user rates the message. Used as a training signal
 *   for RLHF / fine-tuning pipelines and to surface low-rated responses
 *   for human review. Values outside {-1, 0, 1} are rejected by the
 *   Repository.
 *
 * • Three indexes are declared:
 *     1. (user_id, session_id, timestamp) — primary query pattern:
 *        "all messages in session Y for user X in chronological order",
 *        the main chat thread load. Also serves the session list query
 *        (GROUP BY session_id ORDER BY MAX(timestamp) DESC).
 *     2. (user_id, timestamp)             — cross-session history search:
 *        "all messages for user X in last 30 days" for the search feature
 *        and context-window budget calculation without a session filter.
 *     3. (user_id, is_error)              — fast lookup of failed messages
 *        for the retry queue and error analytics dashboard.
 *
 * Architecture layer : Data / Local
 * Table name         : chat_messages
 * Related DAOs       : ChatMessageDao
 * Parent FK          : users.id  (CASCADE delete + update)
 */
@Entity(
        tableName = "chat_messages",
        foreignKeys = {
                @ForeignKey(
                        entity        = UserEntity.class,
                        parentColumns = "id",
                        childColumns  = "user_id",
                        onDelete      = ForeignKey.CASCADE,
                        onUpdate      = ForeignKey.CASCADE
                )
        },
        indices = {
                // Primary: full thread load in chronological order;
                // also serves session-list GROUP BY queries
                @Index(value = {"user_id", "session_id", "timestamp"}),
                // Cross-session history search and token-budget calculation
                @Index(value = {"user_id", "timestamp"}),
                // Failed-message retry queue and error analytics
                @Index(value = {"user_id", "is_error"})
        }
)
public class ChatMessageEntity {

    // ──────────────────────────────────────────────────────────────────────
    // Primary Key
    // ──────────────────────────────────────────────────────────────────────

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    public long id;

    // ──────────────────────────────────────────────────────────────────────
    // Foreign Key
    // ──────────────────────────────────────────────────────────────────────

    /**
     * References {@link UserEntity#id}.
     * Covered by all three composite indexes declared above.
     */
    @ColumnInfo(name = "user_id")
    public long userId;

    // ──────────────────────────────────────────────────────────────────────
    // Session Grouping
    // ──────────────────────────────────────────────────────────────────────

    /**
     * UUID string that groups all messages belonging to one conversation
     * thread. Generated by the Repository (UUID.randomUUID().toString())
     * when the user starts a new chat; shared by all messages in that
     * thread.
     *
     * Not a FK — conversations have no fixed schema row of their own.
     * The session list is derived by:
     *   SELECT session_id, MAX(timestamp) AS last_active
     *   FROM chat_messages
     *   WHERE user_id = :userId
     *   GROUP BY session_id
     *   ORDER BY last_active DESC
     *
     * Format: standard UUID v4, e.g.
     *   "550e8400-e29b-41d4-a716-446655440000"
     */
    @NonNull
    @ColumnInfo(name = "session_id")
    public String sessionId;

    // ──────────────────────────────────────────────────────────────────────
    // Message Core
    // ──────────────────────────────────────────────────────────────────────

    /**
     * The originator of this message.
     * Stored as TEXT via TypeConverters.
     *
     * Expected values (defined in {@link ChatRole}):
     *   USER      — message typed and sent by the human user
     *   ASSISTANT — response generated by the VitalAI AI model
     *
     * Mirrors the role convention used in the Anthropic and OpenAI API
     * message array so chat history can be serialised directly into the
     * API request body without field remapping.
     */
    @NonNull
    @ColumnInfo(name = "role")
    public ChatRole role;

    /**
     * The raw text content of the message.
     *
     * For USER messages    : the user's typed input, unmodified.
     * For ASSISTANT messages: the model's full response, which may
     *   contain markdown (bold, lists, code blocks). The UI layer
     *   renders markdown; the DB stores the raw string.
     * For error messages ({@link #isError} = true): a user-facing
     *   description of the failure (e.g. "I couldn't reach the server.
     *   Please check your connection and try again.").
     */
    @NonNull
    @ColumnInfo(name = "content")
    public String content;

    /**
     * UTC instant at which this message was sent (USER) or received
     * (ASSISTANT). Used as the sort key for thread chronological order
     * and as the "last active" timestamp for the session list.
     * Stored as epoch millis via TypeConverters.
     */
    @NonNull
    @ColumnInfo(name = "timestamp")
    public Date timestamp;

    // ──────────────────────────────────────────────────────────────────────
    // AI Context & Model Metadata
    // ──────────────────────────────────────────────────────────────────────

    /**
     * JSON snapshot of the health context injected into the AI system
     * prompt for this message turn.
     *
     * Structure (illustrative — actual schema defined in the AI layer):
     * {
     *   "recentMetrics": [ { "type": "HEART_RATE", "value": 72, ... } ],
     *   "activeConditions": [ "Type 2 Diabetes" ],
     *   "currentMedications": [ "Metformin 500mg" ],
     *   "lastSleepScore": 68,
     *   "lastWorkout": { "type": "Running", "durationSeconds": 1800 }
     * }
     *
     * Nullable:
     *   • Always null for USER messages.
     *   • Null for ASSISTANT messages generated before context
     *     snapshotting was introduced (legacy rows).
     *   • Null when the message was generated without health context
     *     (e.g. pure conversational small talk).
     *
     * The UI's "Why did VitalAI say this?" explainability panel reads
     * this field to show the user exactly what data the model was given.
     */
    @Nullable
    @ColumnInfo(name = "context_snapshot")
    public String contextSnapshot;

    /**
     * The AI model that generated this ASSISTANT message.
     * Null for USER messages.
     *
     * Examples:
     *   "claude-sonnet-4-20250514" — cloud inference via Anthropic API
     *   "tflite-chat-v1.2"        — on-device model (offline mode)
     *   "rule-engine-v1"          — deterministic scripted response
     *
     * Mirrors {@link InsightEntity#modelVersion} for consistent model
     * auditability across all AI-generated content in VitalAI.
     * Stored for A/B testing, regression detection, and rollback
     * decisions when a model update degrades response quality.
     */
    @Nullable
    @ColumnInfo(name = "model_version")
    public String modelVersion;

    /**
     * Number of tokens consumed by this message as reported by the AI
     * API response ({@code usage.input_tokens + usage.output_tokens}).
     *
     * Used for:
     *   • Context-window budget management — the Repository trims the
     *     oldest messages from the history array sent to the API when
     *     the cumulative token count of the session approaches the
     *     model's context limit.
     *   • Usage analytics — aggregate token consumption per user per
     *     day for capacity planning and potential cost attribution.
     *
     * Nullable:
     *   • Always null for USER messages (token count is an API response
     *     field, not available for outbound messages).
     *   • Null for on-device model responses that do not report token
     *     counts.
     *   • Null for legacy rows inserted before token tracking was added.
     */
    @Nullable
    @ColumnInfo(name = "token_count")
    public Integer tokenCount;

    // ──────────────────────────────────────────────────────────────────────
    // State Flags
    // ──────────────────────────────────────────────────────────────────────

    /**
     * Whether this ASSISTANT message represents a failed model call.
     *
     * FALSE (default) — message was generated successfully.
     * TRUE  — the model call failed (network timeout, API error, content
     *         filter rejection, on-device OOM). In this case
     *         {@link #content} holds the user-facing error description.
     *
     * The UI renders error messages with a distinct style and a "Retry"
     * button. The retry action deletes this row and re-submits the
     * preceding USER message. Always false for USER messages.
     *
     * SQLite stores as INTEGER (0 = false, 1 = true).
     */
    @ColumnInfo(name = "is_error", defaultValue = "0")
    public boolean isError;

    // ──────────────────────────────────────────────────────────────────────
    // User Feedback
    // ──────────────────────────────────────────────────────────────────────

    /**
     * Explicit thumbs-up / thumbs-down rating given by the user for an
     * ASSISTANT message.
     *
     *  1 — thumbs up   (user found the response helpful / accurate)
     * -1 — thumbs down (user found the response unhelpful / inaccurate)
     *  0 — explicitly neutral (reserved for future use)
     * null — not yet rated (default)
     *
     * Only meaningful for ASSISTANT messages; always null for USER
     * messages. The Repository rejects values outside {-1, 0, 1}.
     *
     * Used as a reinforcement-learning signal for fine-tuning pipelines
     * and to surface low-rated responses for human review in the admin
     * dashboard. Displayed in the UI as a thumbs-up / thumbs-down toggle
     * beneath each ASSISTANT message bubble.
     */
    @Nullable
    @ColumnInfo(name = "feedback_rating")
    public Integer feedbackRating;

    // ──────────────────────────────────────────────────────────────────────
    // Timestamps
    // ──────────────────────────────────────────────────────────────────────

    /**
     * UTC instant when this row was first written to the local database.
     * Set once at insert time; never modified thereafter.
     * Distinct from {@link #timestamp} — for ASSISTANT messages,
     * {@code timestamp} reflects when the response was received from the
     * model; {@code createdAt} reflects when the row was persisted locally
     * (the two are usually within milliseconds but may differ under load).
     * Stored as epoch millis via TypeConverters.
     */
    @NonNull
    @ColumnInfo(name = "created_at")
    public Date createdAt;

    /**
     * UTC instant of the most recent update to this row.
     * Updated when {@link #feedbackRating} is set, when an error message
     * is retried (content replaced), or when {@link #tokenCount} is
     * backfilled from a delayed API response.
     * Stored as epoch millis via TypeConverters.
     */
    @NonNull
    @ColumnInfo(name = "updated_at")
    public Date updatedAt;

    // ──────────────────────────────────────────────────────────────────────
    // Constructor
    // ──────────────────────────────────────────────────────────────────────

    /**
     * Full constructor used by the Repository when inserting a new message.
     * Room uses direct field assignment when reading rows back from the DB.
     *
     * @param userId          Local PK of the owning {@link UserEntity}.
     * @param sessionId       UUID of the conversation thread (required).
     * @param role            Message originator — USER or ASSISTANT (required).
     * @param content         Raw message text (required).
     * @param timestamp       Send / receive instant (required).
     * @param contextSnapshot Health context JSON, or null.
     * @param modelVersion    Model identifier, or null.
     * @param tokenCount      API token count, or null.
     * @param isError         True if the model call failed.
     * @param feedbackRating  User rating {-1, 0, 1}, or null.
     * @param createdAt       Insert timestamp (set by Repository).
     * @param updatedAt       Last-update timestamp (set by Repository).
     */
    public ChatMessageEntity(
            long userId,
            @NonNull String sessionId,
            @NonNull ChatRole role,
            @NonNull String content,
            @NonNull Date timestamp,
            @Nullable String contextSnapshot,
            @Nullable String modelVersion,
            @Nullable Integer tokenCount,
            boolean isError,
            @Nullable Integer feedbackRating,
            @NonNull Date createdAt,
            @NonNull Date updatedAt) {

        this.userId          = userId;
        this.sessionId       = sessionId;
        this.role            = role;
        this.content         = content;
        this.timestamp       = timestamp;
        this.contextSnapshot = contextSnapshot;
        this.modelVersion    = modelVersion;
        this.tokenCount      = tokenCount;
        this.isError         = isError;
        this.feedbackRating  = feedbackRating;
        this.createdAt       = createdAt;
        this.updatedAt       = updatedAt;
    }

    // ──────────────────────────────────────────────────────────────────────
    // Convenience factories
    // ──────────────────────────────────────────────────────────────────────

    /**
     * Factory for a USER message. Context snapshot, model version, token
     * count, and feedback rating are always null for user-originated
     * messages. {@code isError} is always false.
     * Timestamps are set to now automatically.
     *
     * @param userId    Local PK of the owning user.
     * @param sessionId UUID of the conversation thread.
     * @param content   The user's typed input.
     * @return Ready-to-insert {@link ChatMessageEntity}.
     */
    public static ChatMessageEntity createUserMessage(
            long userId,
            @NonNull String sessionId,
            @NonNull String content) {

        Date now = new Date();
        return new ChatMessageEntity(
                userId, sessionId, ChatRole.USER, content, now,
                null, null, null, false, null, now, now);
    }

    /**
     * Factory for a successful ASSISTANT message with full metadata.
     * {@code isError} is false; {@code feedbackRating} is null until
     * the user rates the response.
     * Timestamps are set to now automatically.
     *
     * @param userId          Local PK of the owning user.
     * @param sessionId       UUID of the conversation thread.
     * @param content         The model's response text (may contain markdown).
     * @param contextSnapshot Health context JSON injected into the prompt.
     * @param modelVersion    Model identifier string.
     * @param tokenCount      Token count from the API response, or null.
     * @return Ready-to-insert {@link ChatMessageEntity}.
     */
    public static ChatMessageEntity createAssistantMessage(
            long userId,
            @NonNull String sessionId,
            @NonNull String content,
            @Nullable String contextSnapshot,
            @Nullable String modelVersion,
            @Nullable Integer tokenCount) {

        Date now = new Date();
        return new ChatMessageEntity(
                userId, sessionId, ChatRole.ASSISTANT, content, now,
                contextSnapshot, modelVersion, tokenCount,
                false, null, now, now);
    }

    /**
     * Factory for a failed ASSISTANT message. {@code content} should be
     * the user-facing error description. {@code isError} is set to true;
     * all AI metadata fields are null since no model response was received.
     * The UI renders this with an error style and a "Retry" button.
     * Timestamps are set to now automatically.
     *
     * @param userId         Local PK of the owning user.
     * @param sessionId      UUID of the conversation thread.
     * @param errorMessage   User-facing description of the failure.
     * @return Ready-to-insert {@link ChatMessageEntity}.
     */
    public static ChatMessageEntity createErrorMessage(
            long userId,
            @NonNull String sessionId,
            @NonNull String errorMessage) {

        Date now = new Date();
        return new ChatMessageEntity(
                userId, sessionId, ChatRole.ASSISTANT, errorMessage, now,
                null, null, null, true, null, now, now);
    }

    // ──────────────────────────────────────────────────────────────────────
    // Utility
    // ──────────────────────────────────────────────────────────────────────

    /**
     * Records the user's thumbs-up feedback for this ASSISTANT message
     * and stamps {@link #updatedAt}. Call this in the Repository when
     * the user taps the thumbs-up button, then pass the entity to
     * {@code ChatMessageDao.update()}.
     *
     * @throws IllegalStateException if called on a USER message.
     */
    public void ratePositive() {
        if (role == ChatRole.USER) {
            throw new IllegalStateException(
                    "Feedback ratings are only valid for ASSISTANT messages.");
        }
        this.feedbackRating = 1;
        this.updatedAt      = new Date();
    }

    /**
     * Records the user's thumbs-down feedback for this ASSISTANT message
     * and stamps {@link #updatedAt}. Call this in the Repository when
     * the user taps the thumbs-down button, then pass the entity to
     * {@code ChatMessageDao.update()}.
     *
     * @throws IllegalStateException if called on a USER message.
     */
    public void rateNegative() {
        if (role == ChatRole.USER) {
            throw new IllegalStateException(
                    "Feedback ratings are only valid for ASSISTANT messages.");
        }
        this.feedbackRating = -1;
        this.updatedAt      = new Date();
    }

    /**
     * Backfills the token count after a delayed API response and stamps
     * {@link #updatedAt}. Call this in the Repository if the token count
     * arrives separately from the streamed content (e.g. in the final
     * SSE chunk of a streaming response).
     *
     * @param tokenCount Token count reported by the API.
     */
    public void applyTokenCount(int tokenCount) {
        this.tokenCount = tokenCount;
        this.updatedAt  = new Date();
    }

    /**
     * Refreshes {@code updated_at} to the current instant.
     * Call this in the Repository before any partial update via
     * {@code ChatMessageDao.update()}.
     */
    public void touch() {
        this.updatedAt = new Date();
    }

    @Override
    public String toString() {
        return "ChatMessageEntity{"
                + "id=" + id
                + ", userId=" + userId
                + ", sessionId='" + sessionId + '\''
                + ", role=" + role
                + ", content='" + content.substring(0, Math.min(content.length(), 60))
                + (content.length() > 60 ? "..." : "") + '\''
                + ", timestamp=" + timestamp
                + ", modelVersion='" + modelVersion + '\''
                + ", tokenCount=" + tokenCount
                + ", isError=" + isError
                + ", feedbackRating=" + feedbackRating
                + ", createdAt=" + createdAt
                + ", updatedAt=" + updatedAt
                + '}';
    }
}