package com.vitalai.app.data.local.entity;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import com.vitalai.app.domain.model.enums.HydrationSource;

import java.util.Date;

/**
 * HydrationLogEntity
 *
 * Room entity representing a row in the {@code hydration_logs} table.
 * Each row records one discrete fluid intake event logged by or on
 * behalf of a user — a single drink, a bottle, or an imported daily
 * total depending on the ingestion path.
 *
 * Design notes
 * ────────────
 * • Foreign key to {@link UserEntity} uses ON DELETE CASCADE — deleting
 *   a user automatically removes all their hydration logs without any
 *   manual Repository cleanup.
 *
 * • The fundamental unit of measurement is millilitres (mL). All
 *   ingestion paths normalise to mL before inserting; UI conversion
 *   to fl oz is a ViewModel concern only. Using a single canonical
 *   unit keeps SQL aggregations (daily totals, rolling averages)
 *   correct without runtime unit-dispatch logic.
 *
 * • {@code source} maps to {@link HydrationSource} — the origin of
 *   the log entry (e.g. MANUAL, HEALTH_CONNECT, BLE_SMART_BOTTLE,
 *   AI_SUGGESTION, CSV_IMPORT). Stored as TEXT via TypeConverters.
 *   Drives UI provenance badges and is used by the AI layer to weight
 *   entries differently (e.g. a smart-bottle reading is treated as
 *   more reliable than an AI-suggested estimate).
 *
 * • {@code beverageType} is a free-form TEXT label for the fluid
 *   consumed. Storing it as free-form rather than an enum keeps the
 *   set open-ended (users may log herbal teas, electrolyte drinks,
 *   protein shakes, etc.) without requiring migrations for new types.
 *   The AI nutrition layer performs fuzzy matching against an internal
 *   taxonomy at inference time.
 *   Examples: "Water", "Coffee", "Green Tea", "Sports Drink",
 *             "Sparkling Water", "Coconut Water", "Milk".
 *
 * • {@code loggedAt} is the user-reported or device-reported instant
 *   the fluid was consumed — NOT the DB insert time. For manual logs
 *   this is the user-selected time; for HealthConnect it is the
 *   record's {@code time} field; for smart-bottle BLE it is the
 *   device timestamp. This field is the sort key for daily timeline
 *   views and the aggregate key for daily-total queries.
 *
 * • {@code caffeinemg} and {@code sugarG} are optional nutritional
 *   metadata for beverages other than plain water. Used by the AI
 *   nutrition layer to factor caffeine intake into sleep-quality
 *   insights and sugar intake into glucose trend analysis.
 *   Both nullable — plain water entries omit these fields entirely.
 *
 * • {@code isAiSuggested} flags entries that were generated by the
 *   AI hydration coach rather than explicitly logged by the user
 *   (e.g. "VitalAI estimated you drank 250 mL based on your workout
 *   sweat rate"). Displayed with a distinct style in the daily
 *   timeline; can be deleted or confirmed by the user. Defaults to
 *   false for user-initiated and device-sourced logs.
 *
 * • {@code goalId} is an optional soft FK to the {@code goals} table
 *   linking this log entry to the user's active hydration goal. Used
 *   by the Repository to update the goal's {@code currentValue} field
 *   when a new log is inserted, and by the goal detail screen's
 *   "View intake history" deep-link. A typed Room FK is avoided —
 *   deleting a goal must not cascade-delete historical intake logs.
 *   Nullable — logs recorded before a goal existed, or by users with
 *   no active hydration goal, omit this field.
 *
 * • Three indexes are declared:
 *     1. (user_id, logged_at)    — primary query pattern: "all logs for
 *        user X on date D" for the daily timeline view and daily-total
 *        aggregation. Also serves weekly/monthly trend charts.
 *     2. (user_id, source)       — provenance-filtered queries: "all
 *        BLE_SMART_BOTTLE entries for user X" for device sync auditing
 *        and AI-suggested entry management.
 *     3. (user_id, is_ai_suggested) — fast lookup of unconfirmed AI
 *        estimates for the "Review AI suggestions" nudge card.
 *
 * Architecture layer : Data / Local
 * Table name         : hydration_logs
 * Related DAOs       : HydrationLogDao
 * Parent FK          : users.id  (CASCADE delete + update)
 */
@Entity(
        tableName = "hydration_logs",
        foreignKeys = {
                @ForeignKey(
                        entity        = UserEntity.class,
                        parentColumns = "id",
                        childColumns  = "user_id",
                        onDelete      = ForeignKey.CASCADE,
                        onUpdate      = ForeignKey.CASCADE
                )
        },
        indices = {
                // Primary: daily timeline view and daily-total aggregation
                @Index(value = {"user_id", "logged_at"}),
                // Provenance-filtered queries and device sync auditing
                @Index(value = {"user_id", "source"}),
                // AI-suggested entry review nudge card
                @Index(value = {"user_id", "is_ai_suggested"})
        }
)
public class HydrationLogEntity {

    // ──────────────────────────────────────────────────────────────────────
    // Primary Key
    // ──────────────────────────────────────────────────────────────────────

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    public long id;

    // ──────────────────────────────────────────────────────────────────────
    // Foreign Key
    // ──────────────────────────────────────────────────────────────────────

    /**
     * References {@link UserEntity#id}.
     * Covered by all three composite indexes declared above.
     */
    @ColumnInfo(name = "user_id")
    public long userId;

    // ──────────────────────────────────────────────────────────────────────
    // Intake Measurement
    // ──────────────────────────────────────────────────────────────────────

    /**
     * Volume of fluid consumed in millilitres (mL).
     * All ingestion paths normalise to mL before insert.
     *
     * Typical values:
     *   200–250 mL  — small glass / espresso shot
     *   330–355 mL  — standard can
     *   500 mL      — standard bottle
     *   750 mL      — large bottle / sports bottle
     *   1000 mL     — 1-litre bottle
     *
     * Stored as REAL (double) to accommodate fractional values from
     * smart-bottle sensors and AI-estimated amounts, consistent with
     * the {@code value} field in {@link HealthMetricEntity}.
     */
    @ColumnInfo(name = "amount_ml")
    public double amountMl;

    /**
     * The type of fluid consumed.
     * Free-form TEXT — no enum constraint — to accommodate the full
     * breadth of beverages without schema migrations.
     *
     * Common values: "Water", "Coffee", "Tea", "Green Tea",
     *   "Sports Drink", "Sparkling Water", "Juice", "Milk",
     *   "Coconut Water", "Herbal Tea", "Protein Shake", "Smoothie"
     *
     * Nullable — entries imported from HealthConnect or smart-bottle
     * BLE may not carry beverage type metadata. The AI nutrition layer
     * treats null as plain water for hydration calculations.
     */
    @Nullable
    @ColumnInfo(name = "beverage_type")
    public String beverageType;

    // ──────────────────────────────────────────────────────────────────────
    // Intake Instant
    // ──────────────────────────────────────────────────────────────────────

    /**
     * UTC instant when the fluid was consumed (not the DB insert time).
     *
     * For manual logs       : the user-selected time in the log dialog.
     * For HealthConnect     : the {@code time} field of the
     *                         HydrationRecord.
     * For BLE smart bottles : the device-reported pour timestamp.
     * For AI suggestions    : the inferred consumption time based on
     *                         workout end time or scheduled reminder.
     *
     * Used as the sort key for the daily timeline and as the grouping
     * key for daily-total aggregations:
     *   SELECT SUM(amount_ml) FROM hydration_logs
     *   WHERE user_id = :uid
     *     AND logged_at BETWEEN :dayStart AND :dayEnd
     *
     * Stored as epoch millis via TypeConverters.
     */
    @NonNull
    @ColumnInfo(name = "logged_at")
    public Date loggedAt;

    // ──────────────────────────────────────────────────────────────────────
    // Data Provenance
    // ──────────────────────────────────────────────────────────────────────

    /**
     * Origin of this log entry.
     * Stored as TEXT via TypeConverters.
     *
     * Expected values (defined in {@link HydrationSource}):
     *   MANUAL          — tapped the "+" button in the app
     *   HEALTH_CONNECT  — synced from Android Health Connect
     *   BLE_SMART_BOTTLE— streamed from a Bluetooth smart bottle
     *   AI_SUGGESTION   — estimated by the VitalAI hydration coach
     *   CSV_IMPORT      — imported from a user-uploaded CSV file
     *
     * Used by the UI to show provenance badges (e.g. a Bluetooth icon
     * for smart-bottle entries) and by the AI layer to weight entries:
     * BLE and HealthConnect readings are treated as ground truth;
     * AI_SUGGESTION entries are flagged for user confirmation.
     */
    @NonNull
    @ColumnInfo(name = "source")
    public HydrationSource source;

    /**
     * Identifier of the device that recorded this entry.
     * For BLE smart bottles: the device MAC address.
     * For HealthConnect    : the originating app package name.
     * Null for MANUAL, AI_SUGGESTION, and CSV_IMPORT sources.
     */
    @Nullable
    @ColumnInfo(name = "device_id")
    public String deviceId;

    // ──────────────────────────────────────────────────────────────────────
    // Nutritional Metadata
    // ──────────────────────────────────────────────────────────────────────

    /**
     * Caffeine content of this beverage in milligrams (mg).
     *
     * Typical values:
     *   0 mg    — water, herbal tea, most juices
     *   ~95 mg  — standard 240 mL cup of drip coffee
     *   ~63 mg  — standard 240 mL cup of black tea
     *   ~30–50 mg — 240 mL green tea
     *   ~80 mg  — 250 mL energy drink
     *
     * Used by the AI sleep-quality engine to estimate total daily
     * caffeine load and flag late-day intake as a sleep-disruption
     * risk factor. Nullable — plain water and most non-caffeinated
     * beverages omit this field.
     */
    @Nullable
    @ColumnInfo(name = "caffeine_mg")
    public Double caffeineMg;

    /**
     * Sugar content of this beverage in grams (g).
     *
     * Used by the AI nutrition engine to correlate fluid intake with
     * blood glucose trends for users with diabetes or pre-diabetes
     * health conditions. Nullable — water, black coffee, and plain
     * tea entries omit this field.
     */
    @Nullable
    @ColumnInfo(name = "sugar_g")
    public Double sugarG;

    // ──────────────────────────────────────────────────────────────────────
    // AI & Goal Linkage
    // ──────────────────────────────────────────────────────────────────────

    /**
     * Whether this entry was generated by the VitalAI hydration coach
     * rather than explicitly logged by the user or a device.
     *
     * TRUE  — AI estimated this intake (e.g. post-workout rehydration
     *         estimate, scheduled reminder pre-fill). The UI renders
     *         these with a distinct style and a "Confirm / Delete"
     *         action. Confirmed entries have their source updated to
     *         MANUAL by the Repository; deleted entries are hard-deleted.
     * FALSE — user-initiated or device-sourced entry (default).
     *
     * SQLite stores as INTEGER (0 = false, 1 = true).
     */
    @ColumnInfo(name = "is_ai_suggested", defaultValue = "0")
    public boolean isAiSuggested;

    /**
     * Optional soft reference to the {@code goals} table row
     * representing the user's active daily hydration goal.
     *
     * Used by the Repository to update {@link GoalEntity#currentValue}
     * (daily mL total) whenever a new log is inserted or deleted, and
     * by the goal detail screen's "View intake history" deep-link.
     *
     * A typed Room FK is intentionally avoided — deleting a goal must
     * not cascade-delete the historical intake logs accumulated while
     * pursuing it. The Repository validates this ID against the goals
     * table at read time.
     *
     * Nullable — logs recorded before a hydration goal was set, or
     * by users with no active hydration goal, omit this field.
     */
    @Nullable
    @ColumnInfo(name = "goal_id")
    public Long goalId;

    // ──────────────────────────────────────────────────────────────────────
    // Notes
    // ──────────────────────────────────────────────────────────────────────

    /**
     * Optional free-text note attached to this log entry.
     * Examples: "Post-run rehydration", "Morning coffee — felt jittery",
     *           "Forgot to log earlier, estimate".
     * Fed into the AI chat context when the user asks about their
     * hydration habits or caffeine intake patterns.
     */
    @Nullable
    @ColumnInfo(name = "notes")
    public String notes;

    // ──────────────────────────────────────────────────────────────────────
    // Timestamps
    // ──────────────────────────────────────────────────────────────────────

    /**
     * UTC instant when this row was first written to the local database.
     * Set once at insert time; never modified thereafter.
     * Distinct from {@link #loggedAt} — a CSV import may insert rows
     * with historical logged_at times; {@code createdAt} always reflects
     * the actual insert time and is used for sync and audit purposes.
     * Stored as epoch millis via TypeConverters.
     */
    @NonNull
    @ColumnInfo(name = "created_at")
    public Date createdAt;

    /**
     * UTC instant of the most recent update to this row.
     * Updated when {@link #isAiSuggested} is cleared on user confirmation,
     * when {@link #amountMl} is corrected, or when {@link #notes} are edited.
     * Stored as epoch millis via TypeConverters.
     */
    @NonNull
    @ColumnInfo(name = "updated_at")
    public Date updatedAt;

    // ──────────────────────────────────────────────────────────────────────
    // Constructor
    // ──────────────────────────────────────────────────────────────────────

    /**
     * Full constructor used by the Repository when inserting a new log.
     * Room uses direct field assignment when reading rows back from the DB.
     *
     * @param userId         Local PK of the owning {@link UserEntity}.
     * @param amountMl       Volume consumed in mL (required).
     * @param beverageType   Beverage label, or null.
     * @param loggedAt       Consumption instant (required).
     * @param source         Ingestion path (required).
     * @param deviceId       Device identifier, or null.
     * @param caffeineMg     Caffeine content in mg, or null.
     * @param sugarG         Sugar content in g, or null.
     * @param isAiSuggested  True if generated by the AI coach.
     * @param goalId         Soft FK to active hydration goal, or null.
     * @param notes          User note, or null.
     * @param createdAt      Insert timestamp (set by Repository).
     * @param updatedAt      Last-update timestamp (set by Repository).
     */
    public HydrationLogEntity(
            long userId,
            double amountMl,
            @Nullable String beverageType,
            @NonNull Date loggedAt,
            @NonNull HydrationSource source,
            @Nullable String deviceId,
            @Nullable Double caffeineMg,
            @Nullable Double sugarG,
            boolean isAiSuggested,
            @Nullable Long goalId,
            @Nullable String notes,
            @NonNull Date createdAt,
            @NonNull Date updatedAt) {

        this.userId        = userId;
        this.amountMl      = amountMl;
        this.beverageType  = beverageType;
        this.loggedAt      = loggedAt;
        this.source        = source;
        this.deviceId      = deviceId;
        this.caffeineMg    = caffeineMg;
        this.sugarG        = sugarG;
        this.isAiSuggested = isAiSuggested;
        this.goalId        = goalId;
        this.notes         = notes;
        this.createdAt     = createdAt;
        this.updatedAt     = updatedAt;
    }

    // ──────────────────────────────────────────────────────────────────────
    // Convenience factories
    // ──────────────────────────────────────────────────────────────────────

    /**
     * Factory for a fully specified manual log entry — the standard path
     * when the user explicitly records a drink with all metadata known.
     * {@code isAiSuggested} is false; timestamps set to now.
     *
     * @param userId        Local PK of the owning user.
     * @param amountMl      Volume consumed in mL.
     * @param beverageType  Beverage label, or null.
     * @param loggedAt      Consumption instant.
     * @param caffeineMg    Caffeine content in mg, or null.
     * @param sugarG        Sugar content in g, or null.
     * @param goalId        Soft FK to active hydration goal, or null.
     * @param notes         User note, or null.
     * @return Ready-to-insert {@link HydrationLogEntity}.
     */
    public static HydrationLogEntity createManual(
            long userId,
            double amountMl,
            @Nullable String beverageType,
            @NonNull Date loggedAt,
            @Nullable Double caffeineMg,
            @Nullable Double sugarG,
            @Nullable Long goalId,
            @Nullable String notes) {

        Date now = new Date();
        return new HydrationLogEntity(
                userId, amountMl, beverageType, loggedAt,
                HydrationSource.MANUAL, null,
                caffeineMg, sugarG, false,
                goalId, notes, now, now);
    }

    /**
     * Minimal factory for a quick water log — the most common manual
     * entry path (user taps a preset button: "+250 mL water").
     * Beverage type defaults to "Water"; all optional fields are null.
     * Timestamps set to now.
     *
     * @param userId   Local PK of the owning user.
     * @param amountMl Volume consumed in mL.
     * @param goalId   Soft FK to active hydration goal, or null.
     * @return Ready-to-insert {@link HydrationLogEntity}.
     */
    public static HydrationLogEntity createWater(
            long userId,
            double amountMl,
            @Nullable Long goalId) {

        Date now = new Date();
        return new HydrationLogEntity(
                userId, amountMl, "Water", now,
                HydrationSource.MANUAL, null,
                null, null, false,
                goalId, null, now, now);
    }

    /**
     * Factory for a device-sourced log arriving from a BLE smart bottle
     * or Android Health Connect. {@code isAiSuggested} is false.
     * Timestamps set to now.
     *
     * @param userId       Local PK of the owning user.
     * @param amountMl     Volume consumed in mL.
     * @param beverageType Beverage label, or null.
     * @param loggedAt     Device-reported consumption instant.
     * @param source       {@link HydrationSource#BLE_SMART_BOTTLE} or
     *                     {@link HydrationSource#HEALTH_CONNECT}.
     * @param deviceId     Device MAC or app package name.
     * @param goalId       Soft FK to active hydration goal, or null.
     * @return Ready-to-insert {@link HydrationLogEntity}.
     */
    public static HydrationLogEntity createFromDevice(
            long userId,
            double amountMl,
            @Nullable String beverageType,
            @NonNull Date loggedAt,
            @NonNull HydrationSource source,
            @Nullable String deviceId,
            @Nullable Long goalId) {

        Date now = new Date();
        return new HydrationLogEntity(
                userId, amountMl, beverageType, loggedAt,
                source, deviceId,
                null, null, false,
                goalId, null, now, now);
    }

    /**
     * Factory for an AI-suggested log entry — an estimated intake event
     * generated by the hydration coach (e.g. post-workout rehydration
     * estimate). {@code isAiSuggested} is true; the entry is displayed
     * with a "Confirm / Delete" prompt in the daily timeline.
     * Timestamps set to now.
     *
     * @param userId       Local PK of the owning user.
     * @param amountMl     Estimated volume in mL.
     * @param beverageType Estimated beverage type, or null.
     * @param loggedAt     Inferred consumption instant.
     * @param goalId       Soft FK to active hydration goal, or null.
     * @param notes        AI reasoning note shown to the user, or null.
     * @return Ready-to-insert {@link HydrationLogEntity}.
     */
    public static HydrationLogEntity createAiSuggested(
            long userId,
            double amountMl,
            @Nullable String beverageType,
            @NonNull Date loggedAt,
            @Nullable Long goalId,
            @Nullable String notes) {

        Date now = new Date();
        return new HydrationLogEntity(
                userId, amountMl, beverageType, loggedAt,
                HydrationSource.AI_SUGGESTION, null,
                null, null, true,
                goalId, notes, now, now);
    }

    // ──────────────────────────────────────────────────────────────────────
    // Utility
    // ──────────────────────────────────────────────────────────────────────

    /**
     * Confirms an AI-suggested entry: clears {@link #isAiSuggested},
     * changes {@link #source} to MANUAL (the user is now the authority),
     * and stamps {@link #updatedAt}. Call this in the Repository when
     * the user taps "Confirm" on an AI suggestion card, then persist
     * via {@code HydrationLogDao.update()}.
     */
    public void confirmAiSuggestion() {
        this.isAiSuggested = false;
        this.source        = HydrationSource.MANUAL;
        this.updatedAt     = new Date();
    }

    /**
     * Corrects the logged volume (e.g. user adjusts a smart-bottle
     * reading or AI estimate) and stamps {@link #updatedAt}. Call this
     * in the Repository when the user edits an existing entry, then
     * persist via {@code HydrationLogDao.update()}.
     *
     * @param correctedAmountMl The revised volume in mL.
     */
    public void correctAmount(double correctedAmountMl) {
        this.amountMl  = correctedAmountMl;
        this.updatedAt = new Date();
    }

    /**
     * Refreshes {@code updated_at} to the current instant.
     * Call this in the Repository before any partial update via
     * {@code HydrationLogDao.update()}.
     */
    public void touch() {
        this.updatedAt = new Date();
    }

    @Override
    public String toString() {
        return "HydrationLogEntity{"
                + "id=" + id
                + ", userId=" + userId
                + ", amountMl=" + amountMl
                + ", beverageType='" + beverageType + '\''
                + ", loggedAt=" + loggedAt
                + ", source=" + source
                + ", deviceId='" + deviceId + '\''
                + ", caffeineMg=" + caffeineMg
                + ", sugarG=" + sugarG
                + ", isAiSuggested=" + isAiSuggested
                + ", goalId=" + goalId
                + ", createdAt=" + createdAt
                + ", updatedAt=" + updatedAt
                + '}';
    }
}